from go_to_specific_point_on_map import GoToPose
from util import Util
from goforward_and_avoid_obstacle import GoForwardAvoid
#from actions import GetPoseBeforeGazebo
#from occupancy_grid_map import OccupancyGridMap
from character_detector import Identifier